/**
 * PDF Export Hook
 * Generates styled PDF documents for drug info, diet plans, and consultations
 */

import { useCallback, useState } from 'react';
import { jsPDF } from 'jspdf';
import type { DrugInfo, DiagnosisResult } from '../types';

// Colors matching app theme
const COLORS = {
    primary: [16, 185, 129] as [number, number, number],     // Emerald
    secondary: [6, 182, 212] as [number, number, number],    // Cyan
    accent: [139, 92, 246] as [number, number, number],      // Purple
    text: [31, 41, 55] as [number, number, number],          // Dark gray
    muted: [107, 114, 128] as [number, number, number],      // Gray
    warning: [245, 158, 11] as [number, number, number],     // Amber
    danger: [239, 68, 68] as [number, number, number],       // Red
};

interface UsePdfExportReturn {
    exportDrugInfo: (drugInfo: DrugInfo) => void;
    exportDietPlan: (dietContent: string, title?: string) => void;
    exportConsultation: (results: DiagnosisResult[], symptoms: string) => void;
    exportGenericContent: (title: string, content: string) => void;
    isExporting: boolean;
    error: string | null;
}

export function usePdfExport(): UsePdfExportReturn {
    const [isExporting, setIsExporting] = useState(false);
    const [error, setError] = useState<string | null>(null);

    // Helper to add header
    const addHeader = (doc: jsPDF, title: string) => {
        // Title
        doc.setFontSize(24);
        doc.setTextColor(...COLORS.primary);
        doc.text(title, 20, 25);

        // Subtitle
        doc.setFontSize(10);
        doc.setTextColor(...COLORS.muted);
        doc.text('Generated by AI Health Hub', 20, 33);
        doc.text(new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit'
        }), 20, 39);

        // Line separator
        doc.setDrawColor(...COLORS.secondary);
        doc.setLineWidth(0.5);
        doc.line(20, 45, 190, 45);

        return 55; // Return starting Y position for content
    };

    // Helper to add footer
    const addFooter = (doc: jsPDF, pageNum: number) => {
        const pageHeight = doc.internal.pageSize.height;
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.muted);
        doc.text(
            '⚠️ This information is for educational purposes only and does not replace professional medical advice.',
            20,
            pageHeight - 20
        );
        doc.text(`Page ${pageNum}`, 180, pageHeight - 10);
    };

    // Helper to add section
    const addSection = (doc: jsPDF, title: string, y: number): number => {
        doc.setFontSize(14);
        doc.setTextColor(...COLORS.secondary);
        doc.text(title, 20, y);
        return y + 8;
    };

    // Helper to add text with wrapping
    const addWrappedText = (doc: jsPDF, text: string, y: number, maxWidth: number = 170): number => {
        doc.setFontSize(11);
        doc.setTextColor(...COLORS.text);
        const lines = doc.splitTextToSize(text, maxWidth);
        doc.text(lines, 20, y);
        return y + (lines.length * 6);
    };

    // Helper to add bullet list
    const addBulletList = (doc: jsPDF, items: string[], y: number): number => {
        doc.setFontSize(10);
        doc.setTextColor(...COLORS.text);
        let currentY = y;
        items.forEach(item => {
            if (currentY > 270) {
                doc.addPage();
                addFooter(doc, doc.getNumberOfPages());
                currentY = 20;
            }
            doc.text(`• ${item}`, 25, currentY);
            currentY += 6;
        });
        return currentY + 4;
    };

    // Export drug information
    const exportDrugInfo = useCallback((drugInfo: DrugInfo) => {
        setIsExporting(true);
        setError(null);

        try {
            const doc = new jsPDF();
            let y = addHeader(doc, `Drug Report: ${drugInfo.name}`);

            // Basic Info
            doc.setFontSize(11);
            doc.setTextColor(...COLORS.muted);
            doc.text(`Generic Name: ${drugInfo.genericName}`, 20, y);
            y += 6;
            doc.text(`Category: ${drugInfo.category}`, 20, y);
            y += 10;

            // Safety Score
            y = addSection(doc, 'Safety Score', y);
            doc.setFontSize(18);
            const scoreColor = drugInfo.safetyScore >= 70 ? COLORS.primary :
                drugInfo.safetyScore >= 40 ? COLORS.warning : COLORS.danger;
            doc.setTextColor(...scoreColor);
            doc.text(`${drugInfo.safetyScore}/100`, 25, y);
            y += 12;

            // Uses
            if (drugInfo.uses.length > 0) {
                y = addSection(doc, 'Uses', y);
                y = addBulletList(doc, drugInfo.uses, y);
            }

            // Side Effects
            if (drugInfo.sideEffects.length > 0) {
                y = addSection(doc, 'Side Effects', y);
                y = addBulletList(doc, drugInfo.sideEffects, y);
            }

            // Warnings
            if (drugInfo.warnings.length > 0) {
                y = addSection(doc, 'Warnings', y);
                doc.setTextColor(...COLORS.warning);
                y = addBulletList(doc, drugInfo.warnings, y);
            }

            // Alternatives
            if (drugInfo.alternatives.length > 0) {
                y = addSection(doc, 'Alternative Medications', y);
                drugInfo.alternatives.forEach(alt => {
                    if (y > 260) {
                        doc.addPage();
                        addFooter(doc, doc.getNumberOfPages());
                        y = 20;
                    }
                    doc.setFontSize(11);
                    doc.setTextColor(...COLORS.text);
                    doc.text(`${alt.name} (${alt.genericName})`, 25, y);
                    y += 5;
                    doc.setFontSize(9);
                    doc.setTextColor(...COLORS.muted);
                    doc.text(`Safety: ${alt.safetyScore}/100 | ${alt.reason}`, 25, y);
                    y += 8;
                });
            }

            // Natural Alternatives
            if (drugInfo.naturalAlternatives.length > 0) {
                y = addSection(doc, 'Natural Alternatives', y);
                drugInfo.naturalAlternatives.forEach(nat => {
                    if (y > 260) {
                        doc.addPage();
                        addFooter(doc, doc.getNumberOfPages());
                        y = 20;
                    }
                    doc.setFontSize(11);
                    doc.setTextColor(...COLORS.accent);
                    doc.text(nat.name, 25, y);
                    y += 5;
                    doc.setFontSize(9);
                    doc.setTextColor(...COLORS.text);
                    const desc = doc.splitTextToSize(nat.description, 160);
                    doc.text(desc, 25, y);
                    y += desc.length * 5 + 6;
                });
            }

            addFooter(doc, 1);
            doc.save(`Drug_Report_${drugInfo.name.replace(/\s+/g, '_')}.pdf`);
        } catch (err) {
            setError('Failed to generate PDF. Please try again.');
            console.error('PDF export error:', err);
        } finally {
            setIsExporting(false);
        }
    }, []);

    // Export diet plan
    const exportDietPlan = useCallback((dietContent: string, title: string = 'Personalized Diet Plan') => {
        setIsExporting(true);
        setError(null);

        try {
            const doc = new jsPDF();
            let y = addHeader(doc, title);

            // Parse and add content
            const lines = dietContent.split('\n');
            lines.forEach(line => {
                if (y > 270) {
                    doc.addPage();
                    addFooter(doc, doc.getNumberOfPages());
                    y = 20;
                }

                const trimmedLine = line.trim();
                if (!trimmedLine) {
                    y += 4;
                    return;
                }

                // Headers
                if (trimmedLine.startsWith('##')) {
                    y += 4;
                    y = addSection(doc, trimmedLine.replace(/^#+\s*/, ''), y);
                } else if (trimmedLine.startsWith('#')) {
                    y += 6;
                    doc.setFontSize(16);
                    doc.setTextColor(...COLORS.primary);
                    doc.text(trimmedLine.replace(/^#+\s*/, ''), 20, y);
                    y += 8;
                } else if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
                    doc.setFontSize(10);
                    doc.setTextColor(...COLORS.text);
                    const bulletText = trimmedLine.replace(/^[-*]\s*/, '');
                    const wrappedLines = doc.splitTextToSize(`• ${bulletText}`, 165);
                    doc.text(wrappedLines, 25, y);
                    y += wrappedLines.length * 5;
                } else if (/^\d+\./.test(trimmedLine)) {
                    doc.setFontSize(10);
                    doc.setTextColor(...COLORS.text);
                    const wrappedLines = doc.splitTextToSize(trimmedLine, 165);
                    doc.text(wrappedLines, 25, y);
                    y += wrappedLines.length * 5;
                } else {
                    const wrappedLines = doc.splitTextToSize(trimmedLine, 170);
                    doc.setFontSize(10);
                    doc.setTextColor(...COLORS.text);
                    doc.text(wrappedLines, 20, y);
                    y += wrappedLines.length * 5;
                }
            });

            addFooter(doc, 1);
            doc.save(`${title.replace(/\s+/g, '_')}.pdf`);
        } catch (err) {
            setError('Failed to generate PDF. Please try again.');
            console.error('PDF export error:', err);
        } finally {
            setIsExporting(false);
        }
    }, []);

    // Export consultation results
    const exportConsultation = useCallback((results: DiagnosisResult[], symptoms: string) => {
        setIsExporting(true);
        setError(null);

        try {
            const doc = new jsPDF();
            let y = addHeader(doc, 'Health Consultation Report');

            // Symptoms section
            y = addSection(doc, 'Reported Symptoms', y);
            y = addWrappedText(doc, symptoms, y);
            y += 8;

            // Results
            y = addSection(doc, 'Analysis Results', y);
            y += 4;

            results.forEach((result, index) => {
                if (y > 240) {
                    doc.addPage();
                    addFooter(doc, doc.getNumberOfPages());
                    y = 20;
                }

                // Condition name
                doc.setFontSize(12);
                doc.setTextColor(...COLORS.text);
                doc.text(`${index + 1}. ${result.condition}`, 20, y);
                y += 6;

                // Confidence and urgency
                doc.setFontSize(9);
                const urgencyColor = result.urgency === 'emergency' ? COLORS.danger :
                    result.urgency === 'high' ? COLORS.warning :
                        result.urgency === 'medium' ? COLORS.secondary : COLORS.primary;
                doc.setTextColor(...urgencyColor);
                doc.text(`Confidence: ${result.confidence}% | Urgency: ${result.urgency.toUpperCase()}`, 25, y);
                y += 6;

                // Description
                doc.setFontSize(10);
                doc.setTextColor(...COLORS.muted);
                const descLines = doc.splitTextToSize(result.description, 160);
                doc.text(descLines, 25, y);
                y += descLines.length * 5 + 4;

                // Recommended actions
                if (result.recommendedActions.length > 0) {
                    doc.setFontSize(9);
                    doc.setTextColor(...COLORS.text);
                    doc.text('Recommended Actions:', 25, y);
                    y += 5;
                    result.recommendedActions.forEach(action => {
                        if (y > 270) {
                            doc.addPage();
                            addFooter(doc, doc.getNumberOfPages());
                            y = 20;
                        }
                        doc.text(`  • ${action}`, 25, y);
                        y += 5;
                    });
                }
                y += 8;
            });

            addFooter(doc, 1);
            doc.save(`Consultation_Report_${new Date().toISOString().split('T')[0]}.pdf`);
        } catch (err) {
            setError('Failed to generate PDF. Please try again.');
            console.error('PDF export error:', err);
        } finally {
            setIsExporting(false);
        }
    }, []);

    // Export generic content
    const exportGenericContent = useCallback((title: string, content: string) => {
        setIsExporting(true);
        setError(null);

        try {
            const doc = new jsPDF();
            let y = addHeader(doc, title);

            y = addWrappedText(doc, content, y);

            addFooter(doc, 1);
            doc.save(`${title.replace(/\s+/g, '_')}.pdf`);
        } catch (err) {
            setError('Failed to generate PDF. Please try again.');
            console.error('PDF export error:', err);
        } finally {
            setIsExporting(false);
        }
    }, []);

    return {
        exportDrugInfo,
        exportDietPlan,
        exportConsultation,
        exportGenericContent,
        isExporting,
        error
    };
}
